version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=gmarr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=apidata
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - db

  app:
    container_name: fastapi_app
    build: .
    command: uvicorn app.main:app --proxy-headers --forwarded-allow-ips=* --host 0.0.0.0 --port 1111
    volumes:
      - .:/app
    ports:
      - "1111:1111"
    restart: always
    
